### ISSUE TITLE
针对像素画预览的缩放算法设置

### ISSUE THREAD

**Issue by Caramel-Diode** [hemengke1997/vscode-image-manager#16]
有些图片本身是像素画风格的, 所以分辨率会比较低.   
但是管理器视图里的图片都会被缩放成固定尺寸导致这下图片看起来很模糊
我希望能给一个针对图片缩放效果的设置
[参考CSS属性`image-rendering`](https://developer.mozilla.org/zh-CN/docs/Web/CSS/image-rendering)
```css
img {
    image-rendering: pixelated;
}
```
`image-rendering`可用取值
- `auto`
- `smooth`
- `high-quality`
- `pixelated`
- `crisp-edges` 这个值好像不生效
